# Generated by Django 5.2.9 on 2026-01-07 06:05

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('description', models.TextField(blank=True, default='Описания коллекции', null=True, verbose_name='Описания')),
                ('image', models.ImageField(upload_to='photos/collection_avatar/%Y/%m/', verbose_name='photo Коллекции')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новая коллекция')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('hex_code', models.CharField(blank=True, help_text='Например: #FF5733', max_length=7, null=True, verbose_name='HEX код цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='photos/gallery/%Y/%m/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/news/%Y/%m/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название комнаты')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название стиля')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='TypeCarpetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Тип ковра')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='Описания ковра', null=True, verbose_name='Описания')),
                ('image', models.ImageField(blank=True, upload_to='photos/typecarpet_avatar/%Y/%m/', verbose_name='photo тип ковров')),
            ],
            options={
                'verbose_name': 'Тип ковра',
                'verbose_name_plural': 'Типы ковров',
            },
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код Ковра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.carpet_image_upload_to, verbose_name='Изображения')),
                ('watched', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('roll', models.BooleanField(default=False, verbose_name='Рулон')),
                ('material', models.CharField(blank=True, help_text='Например: jun va ipak (шерсть и шелк)', max_length=200, null=True, verbose_name='Материал')),
                ('density', models.CharField(blank=True, help_text='Например: 1 m² ga 2880000 tugun', max_length=100, null=True, verbose_name='Плотность')),
                ('base', models.CharField(blank=True, help_text='Например: paxta (хлопок)', max_length=100, null=True, verbose_name='Основа')),
                ('pile_height', models.CharField(blank=True, help_text='Например: 5mm', max_length=20, null=True, verbose_name='Высота ворса')),
                ('yarn_composition', models.CharField(blank=True, help_text='Например: 100%modal', max_length=100, null=True, verbose_name='Состав нити')),
                ('weight', models.CharField(blank=True, help_text='Например: 2850 gr/m² (+/-7%)', max_length=100, null=True, verbose_name='Вес')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpets', to='catalog.collection', verbose_name='Коллекция')),
                ('colors', models.ManyToManyField(blank=True, related_name='carpets', to='catalog.color', verbose_name='Цвета')),
                ('rooms', models.ManyToManyField(blank=True, related_name='carpets', to='catalog.room', verbose_name='Комнаты')),
                ('styles', models.ManyToManyField(blank=True, related_name='carpets', to='catalog.style', verbose_name='Стили')),
            ],
            options={
                'verbose_name': 'Ковер',
                'verbose_name_plural': 'Ковры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.typecarpetcollection', verbose_name='Тип ковра'),
        ),
    ]