# Generated by Django 5.2.9 on 2026-01-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_aboutpage_homepage_dealeradvantage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Изображение для превью новости', null=True, upload_to='photos/news/%Y/%m/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='NewsContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Текстовый блок'), ('images', 'Блок изображений')], default='text', max_length=10, verbose_name='Тип блока')),
                ('text_content', models.TextField(blank=True, help_text='Используется для текстовых блоков. Поддерживает HTML (CKEditor)', null=True, verbose_name='Текстовое содержание')),
                ('text_content_uz', models.TextField(blank=True, help_text='Используется для текстовых блоков. Поддерживает HTML (CKEditor)', null=True, verbose_name='Текстовое содержание')),
                ('text_content_ru', models.TextField(blank=True, help_text='Используется для текстовых блоков. Поддерживает HTML (CKEditor)', null=True, verbose_name='Текстовое содержание')),
                ('text_content_en', models.TextField(blank=True, help_text='Используется для текстовых блоков. Поддерживает HTML (CKEditor)', null=True, verbose_name='Текстовое содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='catalog.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок контента новости',
                'verbose_name_plural': 'Блоки контента новости',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/news/content/%Y/%m/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись к изображению')),
                ('caption_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись к изображению')),
                ('caption_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись к изображению')),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись к изображению')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('content_block', models.ForeignKey(limit_choices_to={'content_type': 'images'}, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.newscontentblock', verbose_name='Блок контента')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новости',
                'ordering': ['order'],
            },
        ),
    ]
