# Generated by Django 5.2.9 on 2026-01-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_advantagecard_contactformsubmission_contactpage_faq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Главная секция', 'verbose_name_plural': 'Главная секция'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='type',
        ),
        migrations.AddField(
            model_name='carpet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typecarpetcollection', verbose_name='Тип ковра'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.FileField(default='video.mp4', upload_to='files/homepage/%Y/%m/', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
