# Generated by Django 5.2.9 on 2026-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_homepage_options_remove_collection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название стиля'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название стиля'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название стиля'),
        ),
        migrations.AddField(
            model_name='typecarpetcollection',
            name='description_en',
            field=models.TextField(blank=True, default='Описания ковра', null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='typecarpetcollection',
            name='description_ru',
            field=models.TextField(blank=True, default='Описания ковра', null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='typecarpetcollection',
            name='description_uz',
            field=models.TextField(blank=True, default='Описания ковра', null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='typecarpetcollection',
            name='type_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Тип ковра'),
        ),
        migrations.AddField(
            model_name='typecarpetcollection',
            name='type_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Тип ковра'),
        ),
        migrations.AddField(
            model_name='typecarpetcollection',
            name='type_uz',
            field=models.CharField(max_length=32, null=True, verbose_name='Тип ковра'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='salespoint',
            name='map_link',
            field=models.URLField(blank=True, help_text='Ссылка на Google Maps или Яндекс.Карты', max_length=500, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
