# Generated by Django 5.2.9 on 2026-01-26 04:34

import django.db.models.deletion
from django.db import migrations, models


def create_pointtype_if_not_exists(apps, schema_editor):
    """Создать таблицу PointType только если она не существует"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'catalog_pointtype'
            );
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            # Создаем таблицу вручную через SQL
            cursor.execute("""
                CREATE TABLE catalog_pointtype (
                    id BIGSERIAL PRIMARY KEY,
                    name VARCHAR(200) NOT NULL,
                    name_uz VARCHAR(200),
                    name_ru VARCHAR(200),
                    name_en VARCHAR(200),
                    slug VARCHAR(50) UNIQUE NOT NULL,
                    "order" INTEGER NOT NULL DEFAULT 0,
                    is_published BOOLEAN NOT NULL DEFAULT TRUE
                );
            """)


def reverse_create_pointtype(apps, schema_editor):
    """Удалить таблицу PointType при откате миграции"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS catalog_pointtype CASCADE;")


def safe_remove_field(apps, schema_editor, table_name, column_name):
    """Безопасно удалить колонку, если она существует"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = %s
                AND column_name = %s
            );
        """, [table_name, column_name])
        exists = cursor.fetchone()[0]
        
        if exists:
            cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name} CASCADE;')


def remove_fields_safely(apps, schema_editor):
    """Безопасно удалить все поля, которые могут уже не существовать"""
    safe_remove_field(apps, schema_editor, 'catalog_carpet', 'type_id')
    safe_remove_field(apps, schema_editor, 'catalog_aboutpage', 'company_history')
    safe_remove_field(apps, schema_editor, 'catalog_aboutpage', 'production_capacity')
    safe_remove_field(apps, schema_editor, 'catalog_aboutpage', 'production_steps')
    safe_remove_field(apps, schema_editor, 'catalog_gallery', 'description')


def reverse_remove_fields(apps, schema_editor):
    """Обратная операция - ничего не делаем, так как поля уже удалены"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_homepage_options_remove_collection_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_pointtype_if_not_exists,
                    reverse_create_pointtype,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PointType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200, verbose_name='Название типа')),
                        ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Название типа')),
                        ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название типа')),
                        ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название типа')),
                        ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                        ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                        ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                    ],
                    options={
                        'verbose_name': 'Тип точки',
                        'verbose_name_plural': 'Типы точек',
                        'ordering': ['order', 'name'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_fields_safely,
                    reverse_remove_fields,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='carpet',
                    name='type',
                ),
                migrations.RemoveField(
                    model_name='aboutpage',
                    name='company_history',
                ),
                migrations.RemoveField(
                    model_name='aboutpage',
                    name='production_capacity',
                ),
                migrations.RemoveField(
                    model_name='aboutpage',
                    name='production_steps',
                ),
                migrations.RemoveField(
                    model_name='gallery',
                    name='description',
                ),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название стиля'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название стиля'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название стиля'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='salespoint',
            name='map_link',
            field=models.URLField(blank=True, help_text='Ссылка на Google Maps или Яндекс.Карты', max_length=500, null=True, verbose_name='Ссылка на карту'),
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок события')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок события')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок события')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание события')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание события')),
                ('description_en', models.TextField(null=True, verbose_name='Описание события')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/company_history/%Y/%m/', verbose_name='Изображение события')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_history', to='catalog.aboutpage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'История компании',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.AlterField(
            model_name='salespoint',
            name='point_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_points', to='catalog.pointtype', verbose_name='Тип точки'),
        ),
        migrations.CreateModel(
            name='ProductionCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('capacity', models.CharField(max_length=100, verbose_name='Объем производства')),
                ('capacity_uz', models.CharField(max_length=100, null=True, verbose_name='Объем производства')),
                ('capacity_ru', models.CharField(max_length=100, null=True, verbose_name='Объем производства')),
                ('capacity_en', models.CharField(max_length=100, null=True, verbose_name='Объем производства')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/production_capacity/%Y/%m/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_capacity', to='catalog.aboutpage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'Объем производства',
                'verbose_name_plural': 'Объемы производства',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок этапа')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок этапа')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок этапа')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок этапа')),
                ('description', models.TextField(verbose_name='Описание этапа')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание этапа')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание этапа')),
                ('description_en', models.TextField(null=True, verbose_name='Описание этапа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/production_steps/%Y/%m/', verbose_name='Изображение этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='catalog.aboutpage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='TypeCarpetCollection',
        ),
    ]
