# Generated by Django 5.2.9 on 2026-01-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_homepage_options_remove_collection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.DeleteModel(
            name='TypeCarpetCollection',
        ),
    ]
