# Generated by Django 5.2.9 on 2026-01-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_type_carpet_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_history',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='production_capacity',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='production_steps',
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок события')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок события')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок события')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание события')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание события')),
                ('description_en', models.TextField(null=True, verbose_name='Описание события')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/company_history/%Y/%m/', verbose_name='Изображение события')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_history', to='catalog.aboutpage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'История компании',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('capacity', models.CharField(max_length=100, verbose_name='Объем производства')),
                ('capacity_uz', models.CharField(max_length=100, null=True, verbose_name='Объем производства')),
                ('capacity_ru', models.CharField(max_length=100, null=True, verbose_name='Объем производства')),
                ('capacity_en', models.CharField(max_length=100, null=True, verbose_name='Объем производства')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/production_capacity/%Y/%m/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_capacity', to='catalog.aboutpage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'Объем производства',
                'verbose_name_plural': 'Объемы производства',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок этапа')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок этапа')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок этапа')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок этапа')),
                ('description', models.TextField(verbose_name='Описание этапа')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание этапа')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание этапа')),
                ('description_en', models.TextField(null=True, verbose_name='Описание этапа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/production_steps/%Y/%m/', verbose_name='Изображение этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='catalog.aboutpage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства',
                'ordering': ['order'],
            },
        ),
    ]
