# Generated by Django 5.2.9 on 2026-01-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_gallery_description_color_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Название типа')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название типа')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название типа')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Тип точки',
                'verbose_name_plural': 'Типы точек',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='salespoint',
            name='point_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_points', to='catalog.pointtype', verbose_name='Тип точки'),
        ),
    ]
