# Generated by Django 5.2.9 on 2026-01-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pointtype_remove_carpet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscontentblock',
            name='title',
            field=models.CharField(blank=True, help_text='Опциональный заголовок для блока контента', max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='newscontentblock',
            name='title_en',
            field=models.CharField(blank=True, help_text='Опциональный заголовок для блока контента', max_length=200, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='newscontentblock',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Опциональный заголовок для блока контента', max_length=200, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AddField(
            model_name='newscontentblock',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Опциональный заголовок для блока контента', max_length=200, null=True, verbose_name='Заголовок блока'),
        ),
    ]
