# Generated by Django 5.2.9 on 2026-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_title_to_news_content_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='base_en',
            field=models.CharField(blank=True, help_text='Например: paxta (хлопок)', max_length=100, null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='base_ru',
            field=models.CharField(blank=True, help_text='Например: paxta (хлопок)', max_length=100, null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='base_uz',
            field=models.CharField(blank=True, help_text='Например: paxta (хлопок)', max_length=100, null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='density_en',
            field=models.CharField(blank=True, help_text='Например: 1 m² ga 2880000 tugun', max_length=100, null=True, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='density_ru',
            field=models.CharField(blank=True, help_text='Например: 1 m² ga 2880000 tugun', max_length=100, null=True, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='density_uz',
            field=models.CharField(blank=True, help_text='Например: 1 m² ga 2880000 tugun', max_length=100, null=True, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='material_en',
            field=models.CharField(blank=True, help_text='Например: jun va ipak (шерсть и шелк)', max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='material_ru',
            field=models.CharField(blank=True, help_text='Например: jun va ipak (шерсть и шелк)', max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='material_uz',
            field=models.CharField(blank=True, help_text='Например: jun va ipak (шерсть и шелк)', max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='pile_height_en',
            field=models.CharField(blank=True, help_text='Например: 5mm', max_length=20, null=True, verbose_name='Высота ворса'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='pile_height_ru',
            field=models.CharField(blank=True, help_text='Например: 5mm', max_length=20, null=True, verbose_name='Высота ворса'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='pile_height_uz',
            field=models.CharField(blank=True, help_text='Например: 5mm', max_length=20, null=True, verbose_name='Высота ворса'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='weight_en',
            field=models.CharField(blank=True, help_text='Например: 2850 gr/m² (+/-7%)', max_length=100, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='weight_ru',
            field=models.CharField(blank=True, help_text='Например: 2850 gr/m² (+/-7%)', max_length=100, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='weight_uz',
            field=models.CharField(blank=True, help_text='Например: 2850 gr/m² (+/-7%)', max_length=100, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='yarn_composition_en',
            field=models.CharField(blank=True, help_text='Например: 100%modal', max_length=100, null=True, verbose_name='Состав нити'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='yarn_composition_ru',
            field=models.CharField(blank=True, help_text='Например: 100%modal', max_length=100, null=True, verbose_name='Состав нити'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='yarn_composition_uz',
            field=models.CharField(blank=True, help_text='Например: 100%modal', max_length=100, null=True, verbose_name='Состав нити'),
        ),
    ]
