# Generated by Django 5.2.9 on 2026-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_multilang_fields_to_carpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, default='Описания коллекции', null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(blank=True, default='Описания коллекции', null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_uz',
            field=models.TextField(blank=True, default='Описания коллекции', null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pointtype',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='style',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
