# Generated by Django 5.2.9 on 2026-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_collection_description_en_collection_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='code_en',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код Ковра'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='code_ru',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код Ковра'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='code_uz',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код Ковра'),
        ),
    ]
