# Generated by Django 5.2.9 on 2026-01-27 11:28

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_carpet_code_en_carpet_code_ru_carpet_code_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.carpet_gallery_upload_to, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.carpet', verbose_name='Ковер')),
            ],
            options={
                'verbose_name': 'Изображение ковра',
                'verbose_name_plural': 'Изображения ковра',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
