# Generated by Django 5.2.9 on 2026-01-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_update_homepage_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='showroom_link_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='showroom_link_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='showroom_link_uz',
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Например: https://maps.google.com/...', max_length=1000, null=True, verbose_name='Ссылка на Google Maps'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage_subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции преимуществ'),
        ),
    ]
