# Generated by Django 5.2.9 on 2026-01-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_add_multilang_cta_links'),
        ('catalog', '0017_remove_homepage_showroom_link_en_and_more'),
    ]

    operations = [
    ]
