# Generated by Django 5.2.9 on 2026-01-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_merge_20260129_2342'),
        ('catalog', '0019_rework_aboutpage'),
    ]

    operations = [
    ]
