# Generated by Django 5.2.9 on 2026-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_add_image_to_company_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyhistory',
            options={'ordering': ['year'], 'verbose_name': 'История компании', 'verbose_name_plural': 'История компании'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_description_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_description_uz',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_subtitle_uz',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='company_title_uz',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='showroom_button_text_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='showroom_button_text_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='showroom_button_text_uz',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='title_uz',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_banner_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок баннера'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_banner_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок баннера'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_banner_subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок баннера'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_banner_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок баннера'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_banner_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок баннера'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_banner_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок баннера'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "О компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_section_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "О компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_section_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "О компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='canonical_url_en',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='canonical_url_ru',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='canonical_url_uz',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_1_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_1_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_1_subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_1_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_1_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_1_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_2_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_2_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_2_subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_2_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_2_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_2_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_3_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_3_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_3_subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_3_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_3_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_3_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_4_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_4_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_4_subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок карточки 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_4_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_4_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_card_4_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_section_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Объемы производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Объемы производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_section_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Объемы производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_section_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Объемы производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции объемов'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции объемов'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capacity_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции объемов'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_1_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_1_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_1_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_1_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_1_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_1_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_2_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_2_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_2_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_2_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_2_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_2_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_3_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_3_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_3_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_3_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_3_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_card_3_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок карточки 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_section_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Партнерство для дилеров"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Партнерство для дилеров"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_section_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Партнерство для дилеров"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_section_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Партнерство для дилеров"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции для дилеров'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции для дилеров'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='dealer_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции для дилеров'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history_section_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "История компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "История компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history_section_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "История компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history_section_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "История компании"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description_uz',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_description_en',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_description_ru',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_description_uz',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_section_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Процесс производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Процесс производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_section_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Процесс производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_section_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название секции "Процесс производства"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции производства'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции производства'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='production_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок секции производства'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название года'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название года'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='canonical_url_en',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='canonical_url_ru',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='canonical_url_uz',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_description_uz',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='meta_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='og_description_en',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='og_description_ru',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='og_description_uz',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='og_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='og_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='canonical_url_en',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='canonical_url_ru',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='canonical_url_uz',
            field=models.URLField(blank=True, help_text='Канонический URL страницы (опционально)', max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_uz',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_description_en',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_description_ru',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_description_uz',
            field=models.TextField(blank=True, help_text='Описание для социальных сетей', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок для социальных сетей (Facebook, Twitter и т.д.)', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, help_text='Полное содержание новости. Поддерживает HTML (CKEditor)', null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, help_text='Полное содержание новости. Поддерживает HTML (CKEditor)', null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, help_text='Полное содержание новости. Поддерживает HTML (CKEditor)', null=True, verbose_name='Содержание'),
        ),
    ]
