# Generated by Django 5.2.9 on 2026-02-04 00:14

from django.db import migrations, models


def fill_cta_fields(apps, schema_editor):
    """Заполнить NULL значения в полях cta_title и cta_description"""
    HomePage = apps.get_model('catalog', 'HomePage')
    for homepage in HomePage.objects.filter(cta_title__isnull=True):
        homepage.cta_title = ''
        homepage.save(update_fields=['cta_title'])
    for homepage in HomePage.objects.filter(cta_description__isnull=True):
        homepage.cta_description = ''
        homepage.save(update_fields=['cta_description'])


def reverse_fill_cta_fields(apps, schema_editor):
    """Обратная операция - не требуется"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_add_back_cta_fields_to_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_description_en',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_description_ru',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_description_uz',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_description_en',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_description_ru',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_description_uz',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description_en',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description_ru',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description_uz',
            field=models.TextField(blank=True, help_text='Описание страницы для поисковых систем (рекомендуется до 160 символов)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title_uz',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем (рекомендуется до 60 символов)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        # Сначала заполняем NULL значения
        migrations.RunPython(fill_cta_fields, reverse_fill_cta_fields),
        # Затем изменяем поля на обязательные
        migrations.AlterField(
            model_name='homepage',
            name='cta_description',
            field=models.TextField(verbose_name='Описание призыва к действию'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок призыва к действию'),
        ),
    ]
