# Generated by Django 5.2.9 on 2026-02-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_add_seo_fields_to_collection_news_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(help_text='Текст копирайта в футере сайта', max_length=200, verbose_name='Копирайт')),
                ('copyright_uz', models.CharField(help_text='Текст копирайта в футере сайта', max_length=200, null=True, verbose_name='Копирайт')),
                ('copyright_ru', models.CharField(help_text='Текст копирайта в футере сайта', max_length=200, null=True, verbose_name='Копирайт')),
                ('copyright_en', models.CharField(help_text='Текст копирайта в футере сайта', max_length=200, null=True, verbose_name='Копирайт')),
                ('form_modal_title', models.CharField(help_text='Заголовок модального окна для формы обратной связи', max_length=200, verbose_name='Заголовок модального окна формы')),
                ('form_modal_title_uz', models.CharField(help_text='Заголовок модального окна для формы обратной связи', max_length=200, null=True, verbose_name='Заголовок модального окна формы')),
                ('form_modal_title_ru', models.CharField(help_text='Заголовок модального окна для формы обратной связи', max_length=200, null=True, verbose_name='Заголовок модального окна формы')),
                ('form_modal_title_en', models.CharField(help_text='Заголовок модального окна для формы обратной связи', max_length=200, null=True, verbose_name='Заголовок модального окна формы')),
                ('form_modal_text', models.TextField(help_text='Текст в модальном окне для формы обратной связи', verbose_name='Текст модального окна формы')),
                ('form_modal_text_uz', models.TextField(help_text='Текст в модальном окне для формы обратной связи', null=True, verbose_name='Текст модального окна формы')),
                ('form_modal_text_ru', models.TextField(help_text='Текст в модальном окне для формы обратной связи', null=True, verbose_name='Текст модального окна формы')),
                ('form_modal_text_en', models.TextField(help_text='Текст в модальном окне для формы обратной связи', null=True, verbose_name='Текст модального окна формы')),
                ('success_modal_title', models.CharField(help_text='Заголовок модального окна после успешной отправки формы', max_length=200, verbose_name='Заголовок модального окна успеха')),
                ('success_modal_title_uz', models.CharField(help_text='Заголовок модального окна после успешной отправки формы', max_length=200, null=True, verbose_name='Заголовок модального окна успеха')),
                ('success_modal_title_ru', models.CharField(help_text='Заголовок модального окна после успешной отправки формы', max_length=200, null=True, verbose_name='Заголовок модального окна успеха')),
                ('success_modal_title_en', models.CharField(help_text='Заголовок модального окна после успешной отправки формы', max_length=200, null=True, verbose_name='Заголовок модального окна успеха')),
                ('success_modal_text', models.TextField(help_text='Текст в модальном окне после успешной отправки формы', verbose_name='Текст модального окна успеха')),
                ('success_modal_text_uz', models.TextField(help_text='Текст в модальном окне после успешной отправки формы', null=True, verbose_name='Текст модального окна успеха')),
                ('success_modal_text_ru', models.TextField(help_text='Текст в модальном окне после успешной отправки формы', null=True, verbose_name='Текст модального окна успеха')),
                ('success_modal_text_en', models.TextField(help_text='Текст в модальном окне после успешной отправки формы', null=True, verbose_name='Текст модального окна успеха')),
                ('email', models.EmailField(help_text='Email для связи', max_length=254, verbose_name='Email')),
                ('address', models.TextField(help_text='Адрес компании', verbose_name='Адрес')),
                ('address_uz', models.TextField(help_text='Адрес компании', null=True, verbose_name='Адрес')),
                ('address_ru', models.TextField(help_text='Адрес компании', null=True, verbose_name='Адрес')),
                ('address_en', models.TextField(help_text='Адрес компании', null=True, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Номер телефона для связи', max_length=50, verbose_name='Номер телефона')),
                ('tour_3d_link', models.URLField(blank=True, help_text='Ссылка на 3D тур (опционально)', max_length=500, null=True, verbose_name='Ссылка на 3D тур')),
                ('collection_cover_image', models.ImageField(blank=True, help_text='Изображение обложки для страницы коллекций', null=True, upload_to='photos/global_settings/%Y/%m/', verbose_name='Обложка страницы коллекции')),
                ('product_cover_image', models.ImageField(blank=True, help_text='Изображение обложки для страницы продуктов', null=True, upload_to='photos/global_settings/%Y/%m/', verbose_name='Обложка страницы продуктов')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
                'ordering': ['-created_at'],
            },
        ),
    ]
