# Generated by Django 5.2.9 on 2026-02-04 00:22

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_add_global_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_uz',
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_1',
            field=models.TextField(blank=True, help_text='Первый абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_1_en',
            field=models.TextField(blank=True, help_text='Первый абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_1_ru',
            field=models.TextField(blank=True, help_text='Первый абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_1_uz',
            field=models.TextField(blank=True, help_text='Первый абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2',
            field=models.TextField(blank=True, help_text='Второй абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2_en',
            field=models.TextField(blank=True, help_text='Второй абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2_ru',
            field=models.TextField(blank=True, help_text='Второй абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2_uz',
            field=models.TextField(blank=True, help_text='Второй абзац новости. Поддерживает форматирование через CKEditor (жирный, курсив, ссылки, списки и т.д.)', null=True, verbose_name='Абзац 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Главное изображение новости', null=True, upload_to='photos/news/%Y/%m/', verbose_name='Обложка'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.news_image_upload_to, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новости',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
