# Generated by Django 5.2.9 on 2026-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_rework_news_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(help_text='Уникальный идентификатор поста в Instagram', max_length=100, unique=True, verbose_name='Instagram ID')),
                ('post_type', models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео'), ('CAROUSEL_ALBUM', 'Карусель')], max_length=20, verbose_name='Тип поста')),
                ('caption', models.TextField(blank=True, help_text='Текст подписи к посту', null=True, verbose_name='Подпись')),
                ('permalink', models.URLField(help_text='Прямая ссылка на пост в Instagram', max_length=500, verbose_name='Ссылка на пост')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL изображения миниатюры', max_length=500, null=True, verbose_name='URL миниатюры')),
                ('media_url', models.URLField(blank=True, help_text='URL основного изображения или видео', max_length=500, null=True, verbose_name='URL медиа')),
                ('like_count', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Количество комментариев')),
                ('timestamp', models.DateTimeField(help_text='Дата и время публикации поста в Instagram', verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать пост на сайте', verbose_name='Публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Пост Instagram',
                'verbose_name_plural': 'Посты Instagram',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instagram_id'], name='catalog_ins_instagr_523f45_idx'), models.Index(fields=['-timestamp'], name='catalog_ins_timesta_05ddb4_idx'), models.Index(fields=['is_published', '-timestamp'], name='catalog_ins_is_publ_5813bf_idx')],
            },
        ),
    ]
