# Generated by Django 5.2.9 on 2026-02-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_add_instagram_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_description_uz',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_title_ru',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='seo_title_uz',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_description',
            field=models.TextField(blank=True, help_text='SEO описание для страницы коллекций', max_length=160, null=True, verbose_name='SEO Description (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_description_en',
            field=models.TextField(blank=True, help_text='SEO описание для страницы коллекций', max_length=160, null=True, verbose_name='SEO Description (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_description_ru',
            field=models.TextField(blank=True, help_text='SEO описание для страницы коллекций', max_length=160, null=True, verbose_name='SEO Description (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_description_uz',
            field=models.TextField(blank=True, help_text='SEO описание для страницы коллекций', max_length=160, null=True, verbose_name='SEO Description (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_title',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы коллекций', max_length=70, null=True, verbose_name='SEO Title (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_title_en',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы коллекций', max_length=70, null=True, verbose_name='SEO Title (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_title_ru',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы коллекций', max_length=70, null=True, verbose_name='SEO Title (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collections_seo_title_uz',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы коллекций', max_length=70, null=True, verbose_name='SEO Title (Коллекции)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_description',
            field=models.TextField(blank=True, help_text='SEO описание для страницы галереи', max_length=160, null=True, verbose_name='SEO Description (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_description_en',
            field=models.TextField(blank=True, help_text='SEO описание для страницы галереи', max_length=160, null=True, verbose_name='SEO Description (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_description_ru',
            field=models.TextField(blank=True, help_text='SEO описание для страницы галереи', max_length=160, null=True, verbose_name='SEO Description (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_description_uz',
            field=models.TextField(blank=True, help_text='SEO описание для страницы галереи', max_length=160, null=True, verbose_name='SEO Description (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_title',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы галереи', max_length=70, null=True, verbose_name='SEO Title (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_title_en',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы галереи', max_length=70, null=True, verbose_name='SEO Title (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_title_ru',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы галереи', max_length=70, null=True, verbose_name='SEO Title (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gallery_seo_title_uz',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы галереи', max_length=70, null=True, verbose_name='SEO Title (Галерея)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_description',
            field=models.TextField(blank=True, help_text='SEO описание для страницы новостей', max_length=160, null=True, verbose_name='SEO Description (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_description_en',
            field=models.TextField(blank=True, help_text='SEO описание для страницы новостей', max_length=160, null=True, verbose_name='SEO Description (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_description_ru',
            field=models.TextField(blank=True, help_text='SEO описание для страницы новостей', max_length=160, null=True, verbose_name='SEO Description (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_description_uz',
            field=models.TextField(blank=True, help_text='SEO описание для страницы новостей', max_length=160, null=True, verbose_name='SEO Description (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_title',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы новостей', max_length=70, null=True, verbose_name='SEO Title (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_title_en',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы новостей', max_length=70, null=True, verbose_name='SEO Title (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_title_ru',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы новостей', max_length=70, null=True, verbose_name='SEO Title (Новости)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_seo_title_uz',
            field=models.CharField(blank=True, help_text='SEO заголовок для страницы новостей', max_length=70, null=True, verbose_name='SEO Title (Новости)'),
        ),
    ]
