# Generated by Django 5.2.9 on 2026-02-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_add_seo_fields_to_global_settings_and_remove_from_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Материал, Плотность, Основа и т.д.', max_length=200, verbose_name='Название характеристики')),
                ('name_uz', models.CharField(help_text='Например: Материал, Плотность, Основа и т.д.', max_length=200, null=True, verbose_name='Название характеристики')),
                ('name_ru', models.CharField(help_text='Например: Материал, Плотность, Основа и т.д.', max_length=200, null=True, verbose_name='Название характеристики')),
                ('name_en', models.CharField(help_text='Например: Материал, Плотность, Основа и т.д.', max_length=200, null=True, verbose_name='Название характеристики')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='base',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='base_en',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='base_ru',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='base_uz',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='density',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='density_en',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='density_ru',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='density_uz',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material_uz',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='pile_height',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='pile_height_en',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='pile_height_ru',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='pile_height_uz',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='weight_en',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='weight_ru',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='weight_uz',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='yarn_composition',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='yarn_composition_en',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='yarn_composition_ru',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='yarn_composition_uz',
        ),
        migrations.CreateModel(
            name='CarpetCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Значение характеристики для данного ковра', max_length=500, null=True, verbose_name='Значение')),
                ('value_uz', models.CharField(blank=True, help_text='Значение характеристики для данного ковра', max_length=500, null=True, verbose_name='Значение')),
                ('value_ru', models.CharField(blank=True, help_text='Значение характеристики для данного ковра', max_length=500, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(blank=True, help_text='Значение характеристики для данного ковра', max_length=500, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.carpet', verbose_name='Ковер')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpet_values', to='catalog.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика ковра',
                'verbose_name_plural': 'Характеристики ковра',
                'ordering': ['order', 'characteristic__order'],
                'unique_together': {('carpet', 'characteristic')},
            },
        ),
    ]
