# Generated by Django 5.2.9 on 2026-02-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_characteristic_remove_carpet_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL основного изображения или видео', max_length=2000, null=True, verbose_name='URL медиа'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='permalink',
            field=models.URLField(help_text='Прямая ссылка на пост в Instagram', max_length=2000, verbose_name='Ссылка на пост'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL изображения миниатюры', max_length=2000, null=True, verbose_name='URL миниатюры'),
        ),
    ]
