# Generated by Django 5.2.9 on 2026-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_increase_instagram_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_description',
            field=models.TextField(default=1, help_text='Описание формы для заявки на дилерство', verbose_name='Описание формы на дилерство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_description_en',
            field=models.TextField(help_text='Описание формы для заявки на дилерство', null=True, verbose_name='Описание формы на дилерство'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_description_ru',
            field=models.TextField(help_text='Описание формы для заявки на дилерство', null=True, verbose_name='Описание формы на дилерство'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_description_uz',
            field=models.TextField(help_text='Описание формы для заявки на дилерство', null=True, verbose_name='Описание формы на дилерство'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_title',
            field=models.CharField(default=1, help_text='Заголовок формы для заявки на дилерство', max_length=200, verbose_name='Заголовок формы на дилерство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_title_en',
            field=models.CharField(help_text='Заголовок формы для заявки на дилерство', max_length=200, null=True, verbose_name='Заголовок формы на дилерство'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_title_ru',
            field=models.CharField(help_text='Заголовок формы для заявки на дилерство', max_length=200, null=True, verbose_name='Заголовок формы на дилерство'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='dealer_form_title_uz',
            field=models.CharField(help_text='Заголовок формы для заявки на дилерство', max_length=200, null=True, verbose_name='Заголовок формы на дилерство'),
        ),
        migrations.CreateModel(
            name='DealerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя контактного лица', max_length=200, verbose_name='Имя')),
                ('company', models.CharField(help_text='Название компании-заявителя', max_length=300, verbose_name='Название компании')),
                ('email', models.EmailField(help_text='Контактный email для связи', max_length=254, verbose_name='Email')),
                ('message', models.TextField(help_text='Сообщение от заявителя', verbose_name='Текст обращения')),
                ('is_processed', models.BooleanField(default=False, help_text='Заявка обработана менеджером', verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на дилерство',
                'verbose_name_plural': 'Заявки на дилерство',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='catalog_dea_created_b2f1a4_idx'), models.Index(fields=['is_processed', '-created_at'], name='catalog_dea_is_proc_d3ae8b_idx')],
            },
        ),
    ]
