# Generated by Django 5.2.9 on 2026-03-07 15:44
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0040_homepage_instagram_section'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_section_text_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_section_text_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_section_text_uz',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_section_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_section_title_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_section_title_uz',
        ),
    ]
